### PR TITLE
Update node-fetch

### PR DESCRIPTION
**Pull request by mitch7391**
Fix for #2 ; that will stop new users installing the plugin or if old users try to reinstall.

### CODE REVIEW

**Comment by satrik** [comment]
anything less than 3 should be fine. thanks @mitch7391

**Comment by mitch7391** [comment]
Thanks @satrik :)

**Comment by mitch7391** [comment]
Hey @satrik I am a little confused as to how your plug-in registers in Homebridge UI without being published to npm. This means that this update will not flag for an update in Homebridge UI for any users who have installed it. Another thing that confuses me is that the version in Homebridge UI is `v1.0.0`; but the version in your `package.json` is `v0.1.1`.

To get your latest version, I had to use git clone your repo, npm pack and the install it locally.

**Comment by satrik** [comment]
@mitch7391 1. the package is on [npm](https://www.npmjs.com/package/homebridge-hyperion-control) since the beginning. also in homebridge UI you can install it via the plugin search and the update wasn't visible yesterday because I just updated the npm package today.

to your second question, npm uses [semantic versioning](https://semver.org)

**Comment by mitch7391** [comment]
@satrik really sorry about that, I don’t know why I could not find your npm, but yes then everything makes sense again then. Sorry to have rushed you on the publish and thanks again for looking at this :)

**Comment by satrik** [comment]
no problem :)

**Pull request merged**
